### ISSUE TITLE
Add Travis Build to the project

### ISSUE THREAD

**Issue by xxks-kkk** [utsaslab/rustfs#12]
**Is your feature request related to a problem? Please describe.**

To make sure the project can always build correctly for every code pull request merged, we need to have an automatic way to build the project. Also, for every pull request, we want to able to verify the
code can at least pass the build test before doing code review and merge.

**Describe the solution you'd like**

Travis CI is the solution we want to use. However, whether it is possible in our case is doubtful because our code has to be run on top of NVMe SSD. Whether we can simulate the hardware is left
to explore (I highly doubt we can actually do this but there might be some surprises).

**Comment by vishwanath1306** [comment]
I've used Travis CI for a couple of projects, and I don't think there's a possibility of specifying the underlying hardware requirements. However, the code coverage and review process can be automated using it. 

[Travis for Rust](https://docs.travis-ci.com/user/languages/rust/)

I'll try to set up a pipeline for the same.

**Comment by xxks-kkk** [comment]
@thebrahminator Thanks for the comments. There probably not a solution to this issue as the code heavily depends on the underlying hardware.

**Comment by vishwanath1306** [comment]
Ah, I understand. Is there a way I can get started with contributing towards this project? The project wiki is pretty scarce.

**Comment by xxks-kkk** [comment]
@thebrahminator I think you can take a look at these two branches: 1.0-dev-fileSystemToy-wrapper-future and 1.0-dev-fileSystemToy-wrapper. What I'm trying to do is to wrap the Rust-C native bindings with a Rust-friendly FFI. These two branches represent two different philosophies of implementing such FFI. Take a look at those branches and let me know your thoughts. We can then move from there.

**Comment by xxks-kkk** [comment]
Looks like not possible due to the special requirement of SPDK (e.g., requires at lease emulated NVMe SSD).
