### ISSUE TITLE
Use RUSTFLAGS instead of .cargo/config file

### ISSUE THREAD

**Issue by djarotech** [utsaslab/rustfs#13]
> Zeyuan
> -Config now has path hard coded, need to be able to somehow pass in value from say environment variables (may need to parse and replace in build.rs?)
> -Rust seems cannot support both build.rs and config (need confirmation). We rely on the build.rs to generate bindings and we rely on config to compile and link libraries. Are there better solutions?
> 

This issue is related to the problem where .cargo/config does not allow you to use any environmental variables (can use the few predefined ones).
https://doc.rust-lang.org/cargo/reference/environment-variables.html
https://rurust.github.io/cargo-docs-ru/environment-variables.html

It seems redundant to use the .cargo/config to set the rustflags =[ ...], when it is possible to set the RUSTFLAGS environmental variable directly (cargo reads this and uses this on compiler incovations).

RUSTFLAGS would look something like this:
```
$ export RUSTFLAGS="-C link-arg=$SPDK_LIB_DIR/build/lib/libspdk.so"
```

**Comment by xxks-kkk** [comment]
Fixed in #14. Close the issue.
